# -*- coding: utf-8 -*-

common_spam_words_en = [
    "# 1",
    "$$$",
    "100 %",
    "100 % free",
    "100 % satisfied",
    "2 girls 1 cup",
    "2g1c",
    "4 u",
    "50 % off",
    "accept credit cards",
    "acceptance",
    "access",
    "accordingly",
    "account",
    "acrotomophilia",
    "act now",
    "action",
    "ad",
    "additional income",
    "addresses on cd",
    "affordable",
    "alabama hot pocket",
    "alaskan pipeline",
    "all new",
    "amazed",
    "amazing",
    "amazing stuff",
    "anilingus",
    "apeshit",
    "apply now",
    "apply online",
    "arsehole",
    "as seen on",
    "auto email removal",
    "auto erotic",
    "avoid",
    "avoid bankruptcy",
    "avoid bankruptcyaward",
    "awards",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "bangbros",
    "bank",
    "bareback",
    "barely legal",
    "barenaked",
    "bargain",
    "bastard",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "be amazed",
    "be your own boss",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "being a member",
    "beneficiary",
    "best price",
    "bestiality",
    "beverage",
    "bill 1618",
    "billing",
    "billing address",
    "billion",
    "bimbos",
    "birdlock",
    "blood",
    "blow",
    "blow your load",
    "blue waffle",
    "blumpkin",
    "bollocks",
    "bondage",
    "bonus",
    "boss",
    "brand new pager",
    "brown showers",
    "brunette action",
    "bullet vibe",
    "busty",
    "butt",
    "buy",
    "buy direct",
    "buying judgements",
    "buying judgments",
    "cable converter",
    "call",
    "call free",
    "call now",
    "calling creditors",
    "can fit",
    "can't live without",
    "can't live without",
    "cancel",
    "cancel at any time",
    "cannot be combined with any other offer",
    "cards accepted",
    "carpet muncher",
    "carpetmuncher",
    "cash",
    "cash bonus",
    "casino",
    "celebrity",
    "cell phone cancer scam",
    "cellulite",
    "cents on the dollar",
    "certified",
    "chance",
    "cheap",
    "check",
    "check or money order",
    "chocolate rosebuds",
    "circlejerk",
    "claims",
    "claims not to be selling anything",
    "claims to be in accordance with some spam law",
    "claims to be legal",
    "clearance",
    "cleveland steamer",
    "click",
    "click below",
    "click to remove",
    "clover clamps",
    "clusterfuck",
    "collect",
    "collect child support",
    "compare",
    "compare rates",
    "compete for your business",
    "congratulations",
    "consolidate debt and credit",
    "consolidate your debt",
    "coon",
    "coons",
    "coprolagnia",
    "coprophilia",
    "copy accurately",
    "copy dvds",
    "cornhole",
    "cost",
    "costs",
    "creampie",
    "credit",
    "credit bureaus",
    "credit card",
    "credit card offers",    
    "credit check",
    "credit offers",
    "crystal",
    "crystals",
    "cures",
    "cures baldness",
    "darkie",
    "date",
    "date rape",
    "daterape",
    "deal",
    "deals",
    "dear email",
    "dear friend",
    "dear somebody",
    "death",
    "debt",
    "deep throat",
    "deepthroat",
    "dendrophilia",
    "diabetic",
    "diagnostics",
    "diamond",
    "diamonds",
    "dig up dirt on friends",
    "die",
    "died",
    "dingleberries",
    "dingleberry",
    "direct email",
    "direct marketing",
    "dirty pillows",
    "dirty sanchez",
    "discount",
    "do it today",
    "doctor",
    "dog style",
    "doggie style",
    "doggiestyle",
    "doggy style",
    "doggystyle",
    "dolcett",
    "dollar",
    "dollars",
    "domination",
    "dominatrix",
    "dommes",
    "don't delete",
    "don't hesitate",
    "donkey punch",
    "dormant",
    "double dong",
    "double your",
    "double your cash",
    "double your income",
    "dp action",
    "drastically reduced",
    "drugs",
    "dry hump",
    "dvda",
    "earn",
    "earn $",
    "earn extra cash",
    "earn per week",
    "easy terms",
    "eat my ass",
    "ecchi",
    "eliminate debt",
    "email harvest",
    "email marketing",
    "equipment",
    "escort",
    "eunuch",
    "eur",
    "euro",
    "exclusive deal",
    "expect to earn",
    "experience",
    "experts",
    "expire",
    "explode your business",
    "extra",
    "extra cash",
    "extra income",
    "f r e e",
    "faggot",
    "fantastic",
    "fantastic deal",
    "fast cash",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "finance",
    "financial",
    "fingerbang",
    "fix",
    "foot fetish",
    "footjob",
    "for free",
    "for instant access",
    "for just",
    "for just $",
    "for only",
    "for you",
    "form",
    "fortune",
    "free access",
    "free cell phone",
    "free consultation",
    "free dvd",
    "free gift",
    "free grant money",
    "free hosting",
    "free info",
    "free installation",
    "free instant",
    "free investment",
    "free leads",
    "free membership",
    "free money",
    "free offer",
    "free preview",
    "free priority mail",
    "free sample",
    "free trial",
    "free website",
    "freedom",
    "friend",
    "frotting",
    "fuck buttons",
    "fuckin",
    "fucking",
    "fucktards",
    "fudge packer",
    "fudgepacker",
    "full refund",
    "futanari",
    "g-spot",
    "gains",
    "gang bang",
    "gay sex",
    "genitals",
    "get",
    "get it now",
    "get it started",
    "get it paid",
    "get out of debt",
    "get paid",
    "get started now",
    "giant cock",
    "gift certificate",
    "girl on",
    "girl on top",
    "girls gone wild",
    "give it away",
    "giving away",
    "goatcx",
    "goatse",
    "god damn",
    "gokkun",
    "gold",
    "golden shower",
    "goo girl",
    "goodpoop",
    "goregasm",
    "great",
    "great offer",
    "grope",
    "group sex",
    "grow",
    "growth",
    "guarantee",
    "guaranteed",
    "guro",
    "hand job",
    "handjob",
    "hard core",
    "hardcore",
    "hardest",
    "have you been turned down",
    "hello",
    "help",
    "hentai",
    "here",
    "heritage",
    "hidden",
    "hidden assets",
    "hidden charges",
    "home",
    "home based",
    "home employment",
    "homoerotic",
    "honkey",
    "hooker",
    "hormone",
    "hot",
    "hot carl",
    "hot chick",
    "how to kill",
    "how to murder",
    "huge",
    "huge fat",
    "human growth hormone",
    "humping",
    "hurry",
    "if only it were that easy",
    "important information regarding",
    "improvement",
    "in accordance with laws",
    "income",
    "income from home",
    "increase sales",
    "increase traffic",
    "increase your sales",
    "incredible deal",
    "info you requested",
    "information you requested",
    "inherit",
    "inheritance",
    "instant",
    "insurance",
    "intercourse",
    "interest",
    "interested",
    "interesting",
    "internet market",
    "internet marketing",
    "investment",
    "investment decision",
    "jail bait",
    "jailbait",
    "jelly donut",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jizz",
    "join millions",
    "join millions of americans",
    "juggs",
    "junk",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "knobbing",
    "ladies",
    "laser printer",
    "leather restraint",
    "leather straight jacket",
    "leave",
    "legal",
    "lemon party",
    "life",
    "life insurance",
    "lifetime",
    "limited",
    "loading",
    "loan",
    "loans",
    "local",
    "lolita",
    "long distance phone offer",
    "lose",
    "love",
    "lovemaking",
    "lower interest rate",
    "lower interest rates",
    "lower monthly payment",
    "lower your mortgage rate",
    "lowesst",
    "lowest",
    "lowest insurance rates",
    "lowest price",
    "luxury",
    "luxury car",
    "mail in order form",
    "maintained",
    "make $",
    "make me come",
    "make money",
    "male squirting",
    "market",
    "marketing",
    "marketing solutions",
    "mass email",
    "med",
    "medical",
    "medication",
    "medications",
    "medicine",
    "medium",
    "meet singles",
    "member",
    "member stuff",
    "membership",
    "menage a trois",
    "message contains",
    "message contains disclaimer",
    "million",
    "million dollars",
    "millionaire",
    "millionaires",
    "miracle",
    "missionary position",
    "mlm",
    "money",
    "money back",
    "money making",
    "month trial offer",
    "more internet traffic",
    "mortgage",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "muff diver",
    "muffdiving",
    "multi-level marketing",
    "multi level marketing",
    "nambla",
    "name brand",
    "nawashi",
    "need",
    "negro",
    "neonazi",
    "never",
    "new customers only",
    "new domain extensions",
    "nig nog",
    "nigerian",
    "nigga",
    "nigger",
    "nimphomania",
    "nipple",
    "nipples",
    "no age restrictions",
    "no catch",
    "no claim forms",
    "no cost",
    "no credit check",
    "no credit experience",
    "no disappointment",
    "no experience",
    "no fees",
    "no gimmick",
    "no gimmicks",
    "no hidden",
    "no hidden costs",
    "no interests",
    "no inventory",
    "no investment",
    "no medical exams",
    "no middleman",
    "no obligation",
    "no purchase necessary",
    "no questions asked",
    "no refund",
    "no selling",
    "no strings attached",
    "no-obligation",
    "non - stop",
    "non stop",
    "not intended",
    "not junk",
    "not spam",
    "now",
    "now only",
    "nsfw images",
    "nudity",
    "nympho",
    "nymphomania",
    "obese",
    "obesity",
    "obligation",
    "octopussy",
    "offer",
    "offer expires",
    "offers coupon",
    "offer coupon",
    "offer extra cash",
    "offers extra cash",
    "offer free",
    "offers free",
    "off shore",
    "omorashi",
    "once in lifetime",
    "one cup two girls",
    "one guy one jar",
    "one hundred percent free",
    "one hundred percent guaranteed",
    "one time",
    "one time mailing",
    "one-time",
    "online",
    "online biz opportunity",
    "online degree",
    "online marketing",
    "online pharmacy",
    "only",
    "open",
    "opportunity",
    "opt in",
    "order",
    "order now",
    "order shipped by",
    "order status",
    "order today",
    "orders shipped by",
    "outstanding values",
    "overnight",
    "paedophile",
    "paki",
    "panties",
    "panty",
    "passwords",
    "pedo bear",
    "pegging",
    "pennies a day",
    "per day",
    "per week",
    "percent",
    "performance",
    "phone",
    "phone sex",
    "photos",
    "pic",
    "pics",
    "pictures",
    "piece of shit",
    "pill",
    "pills",
    "piss pig",
    "pissing",
    "pisspig",
    "playboy",
    "please read",
    "pleasure",
    "pleasure chest",
    "pleasured",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "poop chute",
    "poopchute",
    "pornography",
    "potential earnings",
    "pre-approved",
    "prescription",
    "presently",
    "price",
    "prices",
    "prince albert piercing",
    "print form signature",
    "print out and fax",
    "priority mail",
    "prize",
    "prizes",
    "problem",
    "produced and sent out",
    "profit",
    "profits",
    "promise",
    "promise you",
    "pthc",
    "pubes",
    "punany",
    "purchase",
    "pure profit",
    "pure profits",
    "queaf",
    "queef",
    "quick",
    "quim",
    "quote",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rate",
    "rates",
    "real thing",
    "rectum",
    "refinance",
    "refinance home",
    "refinanced home",
    "refund",
    "remove in quotes",
    "remove subject",
    "removal",
    "removal instructions",
    "remove",
    "removes wrinkles",
    "reply remove subject",
    "request",
    "requires initial investment",
    "reserves the right",
    "reverse",
    "reverse cowgirl",
    "reverses",
    "reverses aging",
    "revolutionary",
    "rimjob",
    "rimming",
    "risk",
    "risk free",
    "risk - free",
    "risks",
    "rolex",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "round the world",
    "rusty trombone",
    "s 1618",
    "s&m",
    "sadism",
    "safeguard notice",
    "sale",
    "sales",
    "sample",
    "santorum",
    "satisfaction",
    "save up to",
    "scat",
    "schlong",
    "scissoring",
    "score",
    "score with babes",
    "secret",
    "section 301",
    "see for yourself",
    "sell",
    "selll",
    "semen",
    "sent in compliance",
    "serious",
    "serious cash",
    "sexo",
    "shaved beaver",
    "shemale",
    "shibari",
    "shit",
    "shitblimp",
    "shitty",
    "shocking",
    "shopper",
    "shopping spree",
    "shota",
    "shrimping",
    "sign",
    "sign up free today",
    "signup",
    "skeet",
    "slanteye",
    "smut",
    "snatch",
    "snowballing",
    "social security number",
    "sodomize",
    "sodomy",
    "solution",
    "spam",
    "special promotion",
    "spic",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "stainless steel",
    "stimulate",
    "stimulated",
    "stimulation",
    "stock alert",
    "stock disclaimer statement",
    "stock pick",
    "stop",
    "stop snoring",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "strong buy",
    "stuff on sale",
    "style doggy",
    "subject to cash",
    "subject to credit",
    "subscribe",
    "subscriber",
    "subscribers",
    "success",
    "suck",
    "sucks",
    "suicide girls",
    "sultry women",
    "supplies",
    "supplies are limited",
    "supply",
    "swastika",
    "swinger",
    "tainted love",
    "take action",
    "take action now",
    "talks about hidden charges",
    "talks about prizes",
    "taste my",
    "tea bagging",
    "tells you it's an ad",
    "terms",
    "terms and conditions",
    "the best rates",
    "the following form",
    "they keep your money",
    "they're just giving it away",
    "thing",
    "this isn't a scam",
    "this isn't junk",
    "this isn't spam",
    "this won't last",
    "thousands",
    "threesome",
    "throating",
    "tied up",
    "tight white",
    "time limited",
    "today",
    "tongue in a",
    "topless",
    "tosser",
    "towelhead",
    "traffic",
    "tranny",
    "trial",
    "tribadism",
    "tub girl",
    "tubgirl",
    "tushy",
    "twat",
    "twink",
    "twinkie",
    "two girls one cup",
    "undisclosed recipient",
    "undressing",
    "university diplomas",
    "unlimited",
    "unsecured credit",
    "unsecured debt",
    "unsolicited",
    "unsubscribe",
    "upskirt",
    "urethra play",
    "urgent",
    "urophilia",
    "us dollars",
    "vacation",
    "vacation offers",
    "venus mound",
    "vibrator",
    "view",
    "violet wand",
    "visit our website",
    "vorarephilia",
    "wank",
    "want",
    "wants credit card",
    "warranty",
    "we hate spam",
    "we honor all",
    "web traffic",
    "weekend getaway",
    "weight",
    "wetback",
    "what are you waiting for",
    "what's keeping you",
    "while supplies last",
    "while you sleep",
    "white power",
    "who really wins",
    "why pay more",
    "wet",    
    "wife",
    "win",
    "winner",
    "winning",
    "won",
    "work at home",
    "work from home",
    "wrapping men",
    "wrinkled starfish",
    "wrongfully",
    "xx",
    "xxx",
    "yaoi",
    "yellow showers",
    "yiffy",
    "you are a winner",
    "you have been selected",
    "you're a winner",
    "your income",
    "zoophilia"
]

common_spam_words_cz = [
    "automaticky přeložená",
    "automaticky přeložený",
    "automaticky preložená",
    "automaticky preložený",
    "burza",
    "burze",
    "burzou",
    "další příjem",
    "erekce",
    "erekci",
    "loterie",
    "lotérie",
    "loterii",
    "lotérii",
    "gratis",
    "klikněte zde",
    "kliknout",
    "klikni zde",
    "kompletně přírodní",
    "masivní",
    "masivně",
    "milion dolarů",
    "navštivte naši stránku",
    "navštivte stránku",
    "navštívit naši stránku",
    "navštívit stránku",
    "orgasmus",
    "orgie",
    "pojistit",
    "pojištění",
    "půjčka",
    "půjčkou",
    "půjčky",
    "úbytek váhy",
    "sleva",
    "válium",
    "valium",
    "vše přírodní",
    "výhra",
    "vyhra",
    "vyhraj",
    "zadarmo",
    "zaručeno",
    "zaručeně",
    "zaručený",
    "záruka",
    "zcela přírodní",
    "zdarma",
    "zdvojnásobit příjem",
    "zemřela",
    "zemřel",
    "umřel",
    "zemřelý",
    "zhubnout",
    "zhubla",
    "zhubnul",
    "zhubněte",
    "ztráta váhy",
    "zvětšení",
    "zvětšený",
    "zvětšit"
]

forbidden_words = [
    "adult",
    "all natural",
    "anal",
    "anal probe",
    "anus",
    "ass",
    "a@@",
    "a55",
    "ahole",
    "ass hole",
    "ass holes",
    "ass munch",
    "ass bang",
    "ass banged",
    "ass bangs",
    "ass fuck",
    "ass fucker",
    "ass hat",
    "ass ho1e",
    "ass h0le",
    "assmaster",
    "asswipe",
    "asswipes",
    "a@@hole",
    "a55hole",
    "bad credit",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "big black",
    "big breasts",
    "big bucks",
    "big knockers",
    "big tits",
    "blow job",
    "blow jobs",
    "boner",
    "bitch",
    "bitches",
    "billion dollars",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "bitched",
    "bitches",
    "boners",
    "boob",
    "booty call",
    "bootee",
    "bootie",
    "boobs",
    "booty",
    "boobies",
    "bull dyke",
    "bull shit",
    "bull shits",
    "bull shitted",
    "bukkake",
    "bulk email",
    "bung hole",
    "butt cheeks",
    "butt hole",
    "butt fuck",
    "butt fucker",    
    "camel toe",
    "cashcashcash",
    "cam girl",
    "cam slut",
    "cam whore",
    "clit",
    "cl1t",
    "clits",
    "cl1ts",
    "clitoris",
    "click here",
    "climax",
    "cheap meds",
    "cholesterol",
    "confidentially on all orders",
    "cunilingus",
    "cunnilingus",
    "cunts",
    "cunt",
    "cunt face",
    "cunt hunter",
    "cunt lick",
    "cunt licker",
    "coital",
    "cock",
    "cocks",
    "c0ck",
    "c0cks",
    "c.0.c.k",
    "c-0-c-k",
    "c.o.c.k",
    "c-o-c-k",
    "cocain",
    "cocaine",
    "cock smoker",
    "cock sucker",
    "cockblock",
    "cockholster",
    "cockknocker",
    "cum",
    "cum shot",
    "cum shots",
    "cumming",  
    "cum slut",
    "cum stain",  
    "deceased",
    "desire",
    "dick",
    "d1ck",
    "d1cks",
    "dildo",
    "dildos",
    "d1ldo",
    "d1ld0",
    "dyke",
    "dykes",
    "double penetration",
    "erect",
    "erection",
    "ejaculation",
    "ejaculate",
    "erotic",
    "erotism",
    "extasy",
    "extacy",
    "fast viagra delivery",
    "financial freedom",
    "financially independent",
    "fingering",
    "fisting",
    "fisted",
    "free quote",    
    "free quotes",    
    "fuck",
    "fucks",
    "f*ck",
    "fuk",
    "fukk",
    "hard to buy",
    "hard to believe",
    "hard sex",
    "harder erection",
    "hardest erection",
    "harder erections",
    "hardest erections",
    "heroin",
    "herpes",
    "home based business",
    "hookup",
    "hooker",
    "horny",
    "incest",
    "it's effective",
    "jack off",
    "jerk off",
    "jerked",
    "jerk 0ff",
    "limited time",
    "limited time offer",
    "limited time only",
    "lesbian",
    "lesbians",
    "lezbian",
    "lezbians",
    "lottery",
    "lose weight",
    "lose weight spam",
    "lover",
    "massive",
    "masterbate",
    "masterbating",
    "masterbation",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "milfs",
    "mortgage rates",
    "naughty",
    "nude",
    "nudes",
    "only $",
    "orgasm",
    "orgasms",
    "orgasmic",
    "orgies",
    "orgy",
    "pedo phile",
    "pedophilia",
    "pedophiliac",
    "penetrate",
    "penetration",
    "penis",
    "porn",
    "porno",
    "potency",
    "promotional",
    "prozac",
    "p*ssy",
    "pussy",
    "pussy pounder",
    "pussies",
    "p.u.s.s.y",
    "pu$$y",
    "quickie",
    "satisfaction guaranteed",
    "save $",
    "save big money",
    "shaved pussy",
    "s.h.i.t",
    "sh1t",
    "s-h-i-t",
    "search engine listings",
    "search engine",
    "search engines",
    "serious only",
    "sexual",
    "sexually",
    "sex",
    "sexy",
    "slut",
    "sluts",  
    "slut dumper",  
    "sucking",
    "sucked",
    "tit",
    "tits",
    "titties",
    "tit fuck",
    "tit fucker",
    "tittie fucker",
    "titty fuck",
    "titty fucker",
    "titty",
    "teabagging",
    "teen",
    "teens",
    "vagina",
    "valium",
    "viagra",
    "vicodin",
    "virgin",
    "virgins",
    "voyeur",
    "vulva",
    "will not believe your eyes",
    "weed",
    "weenie",
    "weight loss",
    "wet dream",
    "wiener",
    "xanax"
]
