from enum import Enum

# enum of signs of spam
class SpamSigns(Enum):
    RECIPIENT_EMPTY = 1
    BODY_EMPTY = 2
    CONTAINS_ATTACHMENT = 3
    MANY_EMPTY_LINES = 4
    BGSOUND_TAG = 5
    OPEN_HTML_TAG = 6
    UPPERCASE_WORDS = 7
    MISSING_SENDER = 8
    FISHY_SENDER = 9
    MANY_EXTERNAL_LINKS = 10
    INVALID_MESSAGE_ID = 11    
    EMPTY_RECEIVED_FIELD = 12
    NON_ASCII_CHARACTERS = 13
    FISHY_ATTACHMENT_FILENAME = 14
    MANY_FISHY_CHARACTERS = 15
    MANY_FONTS = 16
    MANY_SINGLE_CHARS = 17
